#!/bin/sh
SCRIPT_DIR=$(dirname "$0")
docker build -t i3market/verifiable-credentials ${SCRIPT_DIR}
docker tag i3market/verifiable-credentials registry.gitlab.com/i3-market/code/wp3/t3.1-self-sovereign-identity-and-access-management/verifiable-credentials
