#!/bin/sh
SCRIPT_DIR=$(dirname "$0")
export USER_ID=`id -u`
export GROUP_ID=`id -g`
docker-compose -f "${SCRIPT_DIR}/docker-compose.dev.yaml" --env-file "${SCRIPT_DIR}/.env" up vc-service-app

# docker-compose -f docker-compose.dev.yaml --env-file .env up vc-service-app