version: '3.6'

services:

  vc-service:
    image: registry.gitlab.com/i3-market/code/wp3/t3.1-self-sovereign-identity-and-access-management/verifiable-credentials:release-2.9.5
    container_name: vc-service
    restart: unless-stopped
    ports:
      - 4200:4200
    env_file:
      - vc.env
    volumes:
      - ./volumes/misc:/app/misc
      - ./volumes/database.sqlite:/app/database.sqlite
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true