#!/bin/sh
SCRIPT_DIR=$(dirname "$0")
#${SCRIPT_DIR}/docker-prod-build
docker push registry.gitlab.com/i3-market/code/wp3/t3.1-self-sovereign-identity-and-access-management/verifiable-credentials:release-2
