export { default as apiSpecEndpoint } from './api-spec'
export { default as credentialEndpoint } from './credential'
export { default as didEndpoint } from './did'
export { default as issuerEndpoint } from './issuer'
export { default as presentationEndpoint } from './presentation'